-- RUN AS: SYS
-- Create table: APP_AUDIT_LOGINS
CREATE TABLE APP_AUDIT_LOGINS (
    LOGINS_ID NUMBER,
    SESSION_ID NUMBER,
    USERNAME VARCHAR2(30),
    LOGON_TIME TIMESTAMP,
    LOGOFF_TIME TIMESTAMP,
    IP_ADDRESS VARCHAR2(255),
    AUD_INS_DTTM TIMESTAMP,
    AUD_UPD_DTTM TIMESTAMP
)
/

-- Create a sequence: SEQ_LOGIN_ID for table: APP_AUDIT_LOGINS
CREATE SEQUENCE SEQ_LOGIN_ID
/

-- Create trigger for after LOGON event
CREATE OR REPLACE TRIGGER TRG_AFTER_LOGON
AFTER LOGON
ON DATABASE
BEGIN
    INSERT INTO APP_AUDIT_LOGINS
    VALUES(
        SEQ_LOGIN_ID.NEXTVAL, 
        SYS_CONTEXT('USERENV', 'SESSION_ID'), 
        USER, 
        SYSTIMESTAMP, 
        NULL, 
        SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 
        SYSTIMESTAMP, 
        NULL
    );
END;
/

-- Create trigger for before LOGOFF event
CREATE OR REPLACE TRIGGER TGR_BEFORE_LOGOFF
BEFORE LOGOFF
ON DATABASE
BEGIN
    UPDATE APP_AUDIT_LOGINS
    SET 
        LOGOFF_TIME = SYSTIMESTAMP,
        AUD_UPD_DTTM = SYSTIMESTAMP
    WHERE 
        SESSION_ID = SYS_CONTEXT('USERENV', 'SESSION_ID')
        AND USERNAME = USER 
        AND LOGOFF_TIME = NULL;
END;
/

-- Login as different users and logout after some time.

SELECT * FROM APP_AUDIT_LOGINS;

SELECT * FROM DBA_USERS;